---
title: "Appendix"
author: "Ruiwen Zhou"
date: "2025-12-20"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    number_sections: true
    mathjax: default
---
## Model details
We introduce $\boldsymbol X$, $\boldsymbol y$, and $n$ to be the genotype, phenotype, and sample size from the target minority population and $\boldsymbol{\check\beta}$ to be the joint coefficient estimates from the published studies for the prior majority population. 

## BRIGHT.I

BRIGHT.I with an identity link function, for quantitative traits, binary traits or count traits, implements the penalized objective function below,
\begin{align}
Q_{BRIGHT.I}(\boldsymbol\beta) =& (\boldsymbol y-\boldsymbol X\boldsymbol{\beta})^\top(\boldsymbol y-\boldsymbol X\boldsymbol{\beta})/n \nonumber\\
&+\eta (\boldsymbol{\check\beta}-\boldsymbol{\beta})^\top\widehat{\boldsymbol\Sigma}(\boldsymbol{\check\beta}-\boldsymbol{\beta})+p_{\lambda}(\boldsymbol\beta) + C,\label{eq: BRIGHTi quan}\tag{S1}
\end{align}
where $\widehat{\boldsymbol\Sigma}=\boldsymbol{X}^\top\boldsymbol{X}/n$ and $C$ is a term that does not depend on $\boldsymbol{\beta}$. The first term, $(\boldsymbol y-\boldsymbol X\boldsymbol{\beta})^\top(\boldsymbol y-\boldsymbol X\boldsymbol{\beta})/n$, is the OLS loss function measuring the discrepancy between the working model and the target minority data; the second term $(\boldsymbol{\check\beta}-\boldsymbol{\beta})^\top\widehat{\boldsymbol\Sigma}(\boldsymbol{\check\beta}-\boldsymbol{\beta})$, is a Mahalanobis distance, a special case of the Bregman-divergence, measuring the discrepancy between the working model and the prior information.

BRIGHT.I with a logit link function for Bernoulli outcomes or a log link for Poisson outcomes implements the following objective function,
\begin{align}
Q_{BRIGHT.I}(\boldsymbol\beta) = &-\sum_{i=1}^n \{y_i\boldsymbol{X}_i^\top \boldsymbol\beta+b(\boldsymbol{X}_i^\top \boldsymbol\beta)\}\nonumber\\
&-\eta \sum_{i=1}^n \{\boldsymbol{X}_i^\top \boldsymbol{\check\beta}\boldsymbol{X}_i^\top \boldsymbol\beta+b(\boldsymbol{X}_i^\top \boldsymbol\beta)\}+p_{\lambda}(\boldsymbol\beta)+C,\label{eq: BRIGHTi qual}\tag{S2}
\end{align}
where $C$ is a term that does not depend on $\boldsymbol{\beta}$ and $b(\boldsymbol{X}_i^\top \boldsymbol\beta)=-\log\{1+\exp(\boldsymbol{X}_i^\top \boldsymbol\beta)\}$ or $b(\boldsymbol{X}_i^\top \boldsymbol\beta)=-exp(\boldsymbol{X}_i^\top \boldsymbol\beta)$ corresponds to the binary or count traits with canonical link functions, respectively. The first term, $-\sum_{i=1}^n \{y_i\boldsymbol{X}_i^\top \boldsymbol\beta+b(\boldsymbol{X}_i^\top \boldsymbol\beta)\}$, is the negative log-likelihood measuring the discrepancy between the working model and the target minority data; the second term, $\sum_{i=1}^n \{\boldsymbol{X}_i^\top \boldsymbol{\check\beta}\boldsymbol{X}_i^\top \boldsymbol\beta+b(\boldsymbol{X}_i^\top \boldsymbol\beta)\}$, is a Kullback-Leibler distance \citep{kullback1951information}, a special case of the Bregman-divergence, measuring the discrepancy between the working model and the prior information.

## BRIGHT.S

We copy BRIGHT.S objective function as below,
\begin{align}
Q_{BRIGHT.S}(\boldsymbol\beta) =& B_{\widetilde{\boldsymbol\Sigma}}(\boldsymbol{\hat\beta}||\boldsymbol\beta) + \eta B_{\widetilde{\boldsymbol\Sigma}}(\boldsymbol{\check\beta}||\boldsymbol\beta) + p_{\lambda}(\boldsymbol\beta).\label{eq: BRIGHTs}\tag{2}
\end{align}

As shown in \citet{li2022bregman}, BRIGHTs with an identity link function for quantitative, binary or count traits, can be reduced to 
\begin{align}
Q_{BRIGHT.S}(\boldsymbol\beta)= &\boldsymbol{\beta}^\top \widetilde{\boldsymbol\Sigma}\boldsymbol{\beta}-2\boldsymbol{\beta}^\top\boldsymbol{r}\nonumber\\
&+\eta \left ( \boldsymbol{\beta}^\top \widetilde{\boldsymbol\Sigma}\boldsymbol{\beta}-2\boldsymbol{\beta}^\top\widetilde{\boldsymbol\Sigma}\boldsymbol{\check\beta}\right )+p_{\lambda}(\boldsymbol\beta)+C,\label{eq: BRIGHTs quan}\tag{S3}
\end{align}
where  $r$ is the SNPs-trait correlation and $C$ is constant with regard to $\boldsymbol{\beta}$. 
%We note, in this scenario, $\boldsymbol{\hat\beta}$ is only presented for illustration purposes, the actual implementation does not require the inversion or invertibility of $\widetilde{\boldsymbol\Sigma}$. Furthermore, the BRIGHT.S method will reduce to LASSOsum \citep{mak2017polygenic} when $\eta=0$ and $p_{\lambda}(\boldsymbol\beta)$ is chosen as LASSO penalty. 

With a logit link function for Bernoulli outcomes, a debiased LASSO estimator, $\boldsymbol{\hat\beta}=\boldsymbol{\hat b}+\widehat{\boldsymbol\Theta}(\boldsymbol r - \boldsymbol{\hat r})$, ensures a valid approximation of $B_{\widetilde{\boldsymbol\Sigma}}(\boldsymbol{\hat\beta}||\boldsymbol\beta)$ to the negative log-likelihood of logistic regression \citep{cai2021individual}, where $\boldsymbol{\hat b}$ is the published LASSO estimator from the minority study, $\widehat{\boldsymbol\Theta}$ is a regularized inverse of the observed information matrix, and $\boldsymbol{\hat r}=\frac{expit(\boldsymbol X\boldsymbol{\hat b})^\top\boldsymbol X}{n}$ is the marginal marker-predicted outcome inner product, where $expit(\cdot)$ is the inverse of logit function. Then, the objective function in (2) is reduced to
\begin{align}
Q_{BRIGHT.S}(\boldsymbol\beta)=&(\boldsymbol{\beta}-\boldsymbol{\hat b})^\top
\boldsymbol{\widetilde\Sigma}
(\boldsymbol{\beta}-\boldsymbol{\hat b}) +2(\boldsymbol r -\boldsymbol{\hat r})^\top(\boldsymbol{\beta}-\boldsymbol{\hat b})\nonumber\\
&+\eta  \left ( \boldsymbol{\beta}^\top \widetilde{\boldsymbol\Sigma}\boldsymbol{\beta}-2\boldsymbol{\beta}^\top\widetilde{\boldsymbol\Sigma}\boldsymbol{\check\beta}\right )+p_{\lambda}(\boldsymbol\beta)+C,
\label{eq: BRIGHTs qual}\tag{S4}
\end{align}
where $C$ is constant with regard to $\boldsymbol{\beta}$.
We note the actual implementation does not require the debiasing of the LASSO estimator or obtaining $\widehat{\boldsymbol\Theta}$, only $\boldsymbol{\hat b}$ and $\boldsymbol{\hat r}$ are required in addition to $\widetilde{\boldsymbol\Sigma}$, $\boldsymbol r$ and $\boldsymbol{\tilde\beta}$.

## LASSOsum review

LASSOsum implements the objective function below,
\begin{align}
Q_{LASSOsum}(\boldsymbol\beta)= &\boldsymbol{\beta}^\top [(1-s)\widetilde{\boldsymbol\Sigma}+sI]\boldsymbol{\beta}-2\boldsymbol{\beta}^\top\boldsymbol{r}+||\boldsymbol\beta||_1,\label{eq: BRIGHTs quan}\tag{S5}
\end{align}

When $\eta=0$ and $p_{\lambda}(\boldsymbol\beta)=(1-s)||\boldsymbol\beta||_2+||\boldsymbol\beta||_1$, the BRIGHTs objective function in (S3) is reduced to LASSOsum objective function.

## Retrieve r from GWAS

GWAS aim to find marginally significant SNPs associated with the trait of interest. GWAS summary statistics usually include data sample size, coefficient estimates, t-statistics and p-values of marginal single SNP-trait association t-tests from simple linear regressions (SLR), $$\boldsymbol y=a_j+\boldsymbol{X}_{\cdot j} b_j+\epsilon.$$ Therefore, the standardized $\boldsymbol r$, $\boldsymbol r'$, can be retrieved from the t-statistics and data sample size, $$r_j'=\frac{t_j}{\sqrt{t_j^2+n-2}},$$ where $t_j$ is the t-statistic for SNP $j$. In the case where t-statistics are not directly recorded in the GWAS summary statistics, they can also be retrieved from sample size, association direction, $\boldsymbol{S}$, and p-values $\boldsymbol{P}$, $$t_j=S_j\times Q_t(P_j/2,n-2),$$ where $Q_t(P_j/2,n-2)$ is the upper $P_j/2$ quantile of t-distribution with degree of freedom $n-2$ and $j$ is the SNP index.

In the case, where only the GWAS summary statistic information is available, only the standardized $\boldsymbol r_j'$ can be retrieved for model fitting. As a result, the BRIGHT model can only be implemented on the standardized genotype matrix and standardized outcome, which is sufficient for risk classification but cannot predict the outcome in the original scale. If researchers can also get access to the de-identified mean and variance estimate of each genotype, $\boldsymbol{\overline X}_{\cdot j}$ and $\widehat{Var}(\boldsymbol{X}_{\cdot j})$, and outcome, $\boldsymbol{\overline{y}}$ and $\widehat{Var}(\boldsymbol y)$, the original $\boldsymbol r_j:=\boldsymbol{X}_{\cdot j}^\top\boldsymbol y/n$ can be retrieved from the following equation:
$$\boldsymbol r_j=(n-1)\boldsymbol r_j'\sqrt{\widehat{Var}(\boldsymbol{X}_{\cdot j})\widehat{Var}(\boldsymbol y)}+n\boldsymbol{\overline X}_{\cdot j}\boldsymbol{\overline{y}}.$$
Then the original unstandardized BRIGHT model can be fitted.

## LD construction

Minority reference LD is required in the model fitting of BRIGHT.S with either continuous or binary outcomes. However, the full LD matrix imposes computation and estimation issues due to its $p\times p$ scale. In the package we implement the LD based on the block structure information from \cite{berisa2016approximately}. We provide default pre-calculated block-structured LDs for different ancestry based on the preprocessed 1000 Genomes Project cohorts \citep{siva20081000}. The preprocessing of 1000 Genomes Project cohorts includes subsetting HapMap3 SNPs \citep{altshuler2010integrating} and filtering SNPs, which have minor allele frequency (MAF) larger than 0.05 and missing rate below 0.01. As a result, 471,965 SNPs remained after preprocessing. We provide both standardized/unstandardized and hg19/hg38 versions of LD reference from 1000 Genomes Projects cohorts. In addition, both standardized and unstandardized LD can be automatically constructed by utilizing user-specified genotype data in Plink binary format (.bed, .bim and .fam) \citep{purcell2007plink}. We note for user-specified LD construction, it is user's responsibility to preprocess the genotype data and provide the build that matches the summary statistics.

# model selection

# Integration of multiple external models